apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: sink-s3-tpu-tipo-agente-venda-tag
  namespace: kafka
  labels:
    strimzi.io/cluster: connect-v2
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    # Tópico fonte
    topics: "src-meu-topico"
    
    # S3 Config (AJUSTAR OBRIGATORIAMENTE)
    s3.bucket.name: ""
    s3.region: "us-east-1"
    aws.access.key.id: ""
    aws.secret.access.key: ""

    topics.dir: "teste/raw/oracle/SCHEMA"
    
    # CONFIGURAÇÃO OBRIGATÓRIA QUE ESTAVA FALTANDO
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    
    # Formato simples
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: false
    
    # Particionamento (opcional, mas recomendado)
    partitioner.class: "io.confluent.connect.storage.partitioner.DefaultPartitioner"
    
    # Flush a cada 100 mensagens ou 1 minuto
    flush.size: 100
    rotate.interval.ms: 60000
    
    # Configurações adicionais recomendadas
    s3.part.size: 5242880  # 5MB
    s3.compression.type: "gzip"